import { PresetStyle } from '@/types';

export const PRESETS: PresetStyle[] = [
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Clean lines, neutral tones, and functional elegance',
    thumbnail: '/presets/modern-minimal.jpg',
    settings: {
      designStyle: 'Minimalist Modern',
      colorPalette: 'Neutral whites, grays, and black accents',
      atmosphere: 'Bright, airy, and spacious',
      woodFinish: 'Light oak or white-washed',
      metalAccents: 'Brushed nickel or matte black',
      furnitureStyle: 'Sleek, low-profile pieces with clean lines',
      seating: 'Modern sectional or streamlined sofa',
      wallDecor: 'Large abstract art or minimal gallery wall',
      rugStyle: 'Geometric patterns or solid neutral',
      windowTreatments: 'Sheer curtains or modern blinds',
      greenery: 'Minimal statement plants (snake plant, monstera)',
      texture: 'Smooth surfaces with subtle textiles',
      accents: 'Monochromatic throw pillows',
      lighting: 'Recessed lighting with modern pendant fixtures',
      storage: 'Hidden, built-in solutions',
      consistency: 'Very cohesive across all rooms',
      pricePoint: 'Mid-range quality with investment pieces',
    },
  },
  {
    id: 'warm-cozy',
    name: 'Warm & Cozy',
    description: 'Inviting spaces with rich textures and warm tones',
    thumbnail: '/presets/warm-cozy.jpg',
    settings: {
      designStyle: 'Contemporary Cozy',
      colorPalette: 'Warm beiges, soft browns, and cream',
      atmosphere: 'Warm, inviting, and comfortable',
      woodFinish: 'Medium to dark walnut',
      metalAccents: 'Warm brass or bronze',
      furnitureStyle: 'Plush, comfortable pieces with rounded edges',
      seating: 'Overstuffed sofa with deep cushions',
      wallDecor: 'Framed family photos or nature prints',
      rugStyle: 'Plush, textured area rugs',
      windowTreatments: 'Layered curtains with sheers',
      greenery: 'Abundant soft plants',
      texture: 'Layered textiles (knit throws, velvet pillows)',
      accents: 'Mixed patterns in warm tones',
      lighting: 'Warm ambient lighting with table lamps',
      storage: 'Open shelving with decorative baskets',
      consistency: 'Coordinated but varied',
      pricePoint: 'Great value with cozy appeal',
    },
  },
  {
    id: 'luxe-elegant',
    name: 'Luxe Elegant',
    description: 'Sophisticated glamour with high-end finishes',
    thumbnail: '/presets/luxe-elegant.jpg',
    settings: {
      designStyle: 'Luxury Contemporary',
      colorPalette: 'Rich jewel tones, metallics, deep neutrals',
      atmosphere: 'Sophisticated and luxurious',
      woodFinish: 'Rich espresso or exotic woods',
      metalAccents: 'Polished gold, brass, or chrome',
      furnitureStyle: 'Statement pieces with refined details',
      seating: 'Tufted velvet sofa or designer pieces',
      wallDecor: 'Large-scale art or ornate mirrors',
      rugStyle: 'Persian or high-pile luxury rugs',
      windowTreatments: 'Floor-to-ceiling drapes with hardware',
      greenery: 'Sculptural statement plants',
      texture: 'Rich fabrics (velvet, silk, leather)',
      accents: 'Metallic and jewel-toned accessories',
      lighting: 'Chandelier or designer fixtures',
      storage: 'Custom built-ins with display',
      consistency: 'Very cohesive high-end aesthetic',
      pricePoint: 'Luxury investment pieces',
    },
  },
  {
    id: 'scandinavian-bright',
    name: 'Scandinavian Bright',
    description: 'Light, airy spaces with natural elements',
    thumbnail: '/presets/scandinavian.jpg',
    settings: {
      designStyle: 'Scandinavian',
      colorPalette: 'White, light gray, with soft pastels',
      atmosphere: 'Bright, fresh, and tranquil',
      woodFinish: 'Light blonde wood or birch',
      metalAccents: 'Brushed steel or minimal black',
      furnitureStyle: 'Simple, functional, organic shapes',
      seating: 'Mid-century inspired with clean lines',
      wallDecor: 'Minimal botanical prints or photography',
      rugStyle: 'Natural jute or geometric patterns',
      windowTreatments: 'Minimal or sheer whites',
      greenery: 'Natural plants in simple pots',
      texture: 'Natural textiles (linen, cotton, wool)',
      accents: 'Muted colors with natural materials',
      lighting: 'Natural light maximized, pendant fixtures',
      storage: 'Open shelving with minimal display',
      consistency: 'Very cohesive Nordic aesthetic',
      pricePoint: 'Mid-range quality, timeless design',
    },
  },
  {
    id: 'industrial-chic',
    name: 'Industrial Chic',
    description: 'Urban edge with raw materials and vintage touches',
    thumbnail: '/presets/industrial.jpg',
    settings: {
      designStyle: 'Industrial Modern',
      colorPalette: 'Charcoal, brick red, raw metal tones',
      atmosphere: 'Urban, edgy, and authentic',
      woodFinish: 'Reclaimed or distressed wood',
      metalAccents: 'Raw iron, aged brass, or steel',
      furnitureStyle: 'Mix of vintage and modern industrial',
      seating: 'Leather sofa or metal frame pieces',
      wallDecor: 'Exposed brick, metal art, vintage signs',
      rugStyle: 'Distressed or vintage patterns',
      windowTreatments: 'Metal blinds or minimal',
      greenery: 'Hardy plants in metal containers',
      texture: 'Raw materials (concrete, metal, leather)',
      accents: 'Vintage industrial accessories',
      lighting: 'Edison bulbs, metal pendant lights',
      storage: 'Open metal shelving units',
      consistency: 'Cohesive industrial vibe',
      pricePoint: 'Mid-range with vintage finds',
    },
  },
  {
    id: 'bohemian-eclectic',
    name: 'Bohemian Eclectic',
    description: 'Colorful, artistic spaces with global influences',
    thumbnail: '/presets/bohemian.jpg',
    settings: {
      designStyle: 'Bohemian Eclectic',
      colorPalette: 'Rich earth tones with vibrant accents',
      atmosphere: 'Relaxed, artistic, and personal',
      woodFinish: 'Natural or dark stained wood',
      metalAccents: 'Mixed metals (copper, brass, iron)',
      furnitureStyle: 'Mix of vintage, global, and handmade',
      seating: 'Low seating, floor cushions, vintage sofa',
      wallDecor: 'Gallery wall with mixed art and textiles',
      rugStyle: 'Layered vintage and ethnic rugs',
      windowTreatments: 'Patterned curtains or macramé',
      greenery: 'Abundant plants everywhere',
      texture: 'Heavily layered (macramé, woven, fringe)',
      accents: 'Colorful, patterned, globally-inspired',
      lighting: 'String lights, Moroccan lamps, natural light',
      storage: 'Open shelving with displayed collections',
      consistency: 'Eclectic but curated aesthetic',
      pricePoint: 'Budget-friendly with unique pieces',
    },
  },
  {
    id: 'farmhouse-rustic',
    name: 'Farmhouse Rustic',
    description: 'Warm, cozy spaces with rustic charm and vintage appeal',
    thumbnail: '/presets/farmhouse.jpg',
    settings: {
      designStyle: 'Modern Farmhouse',
      colorPalette: 'Whites, creams, with warm wood tones',
      atmosphere: 'Cozy, welcoming, and lived-in',
      woodFinish: 'Weathered pine or distressed oak',
      metalAccents: 'Aged iron, galvanized steel, or bronze',
      furnitureStyle: 'Sturdy, oversized pieces with vintage character',
      seating: 'Deep farmhouse sofa with slipcov ers',
      wallDecor: 'Shiplap, vintage signs, family photos',
      rugStyle: 'Natural jute or vintage Persian',
      windowTreatments: 'Simple linen curtains or wooden blinds',
      greenery: 'Fresh flowers, herbs, potted plants',
      texture: 'Natural linens, cotton, burlap',
      accents: 'Mason jars, wicker baskets, antique finds',
      lighting: 'Wrought iron chandeliers, lanterns',
      storage: 'Barn doors, open shelving, vintage cabinets',
      consistency: 'Cohesive rustic aesthetic',
      pricePoint: 'Mid-range with vintage pieces',
    },
  },
  {
    id: 'mid-century-modern',
    name: 'Mid-Century Modern',
    description: 'Retro-inspired with organic forms and bold accents',
    thumbnail: '/presets/mid-century.jpg',
    settings: {
      designStyle: 'Mid-Century Modern',
      colorPalette: 'Warm woods, mustard, teal, burnt orange',
      atmosphere: 'Retro, stylish, and functional',
      woodFinish: 'Teak, walnut, or natural oak',
      metalAccents: 'Brass hairpin legs, gold accents',
      furnitureStyle: 'Low-profile with tapered legs and organic curves',
      seating: 'Iconic mid-century sofa or lounge chair',
      wallDecor: 'Abstract geometric art, sunburst mirrors',
      rugStyle: 'Geometric patterns with bold colors',
      windowTreatments: 'Horizontal blinds or simple panels',
      greenery: 'Statement plants in ceramic planters',
      texture: 'Smooth wood, leather, and nubby fabrics',
      accents: 'Atomic age accessories, ceramic pieces',
      lighting: 'Sputnik chandelier, arc floor lamps',
      storage: 'Credenzas, floating shelves',
      consistency: 'Very cohesive retro aesthetic',
      pricePoint: 'Mid-range to investment pieces',
    },
  },
  {
    id: 'transitional',
    name: 'Transitional',
    description: 'Perfect blend of traditional comfort and modern simplicity',
    thumbnail: '/presets/transitional.jpg',
    settings: {
      designStyle: 'Transitional',
      colorPalette: 'Soft neutrals with subtle color accents',
      atmosphere: 'Balanced, comfortable, and timeless',
      woodFinish: 'Medium tones in oak or maple',
      metalAccents: 'Brushed nickel or oil-rubbed bronze',
      furnitureStyle: 'Mix of traditional and contemporary lines',
      seating: 'Tailored sofa with subtle details',
      wallDecor: 'Mix of classic and modern art',
      rugStyle: 'Traditional patterns in modern colors',
      windowTreatments: 'Classic panels with clean hardware',
      greenery: 'Tasteful plants in classic containers',
      texture: 'Layered soft fabrics (velvet, linen, silk)',
      accents: 'Balanced mix of old and new',
      lighting: 'Updated classics (drum shades, simple chandeliers)',
      storage: 'Built-ins with clean details',
      consistency: 'Cohesive but not matchy',
      pricePoint: 'Mid to high-range quality',
    },
  },
];

export function getPresetById(id: string): PresetStyle | undefined {
  return PRESETS.find((p) => p.id === id);
}

export function getPresetNames(): string[] {
  return PRESETS.map((p) => p.name);
}
